import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner"
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { AuthDialog } from "@/components/auth/auth-dialog"

import { Header } from "@/components/layout/header"
import { Footer } from "@/components/layout/footer"
import { createClient } from "@/utils/supabase/server"
import { GlobalLoaderProvider } from "@/providers/global-loader-provider"
import { GlobalLoader } from "@/components/ui/global-loader"

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  // Admin Check
  let isAdmin = false;
  if (user) {
    if (user.email === 'ekap@ekap.ai') {
        isAdmin = true;
    } else {
        const { data: profile } = await supabase
            .from('profiles')
            .select('role')
            .eq('id', user.id)
            .single();
        if (profile?.role === 'admin') isAdmin = true;
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <NuqsAdapter>
           <GlobalLoaderProvider>
              <Header user={user} isAdmin={isAdmin} />
              <main>
                  {children}
              </main>
              <Footer />
              <Suspense fallback={null}>
                <AuthDialog />
              </Suspense>
              <Toaster richColors />
              <GlobalLoader />
           </GlobalLoaderProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
