import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ReferralTracker } from "@/components/referral-tracker"
import { Toaster } from "@/components/ui/sonner"
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { AuthDialog } from "@/components/auth/auth-dialog"
import { VerificationToast } from "@/components/auth/verification-toast"
import NextTopLoader from 'nextjs-toploader';

import { Header } from "@/components/layout/header"
import { Footer } from "@/components/layout/footer"
import { createClient } from "@/utils/supabase/server"
import { GlobalLoaderProvider } from "@/providers/global-loader-provider"
import { GlobalLoader } from "@/components/ui/global-loader"

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  // Admin Check
  let isAdmin = false;
  if (user) {
    if (user.email === 'ekap@ekap.ai') {
        isAdmin = true;
    } else {
        const { data: profile } = await supabase
            .from('profiles')
            .select('role')
            .eq('id', user.id)
            .single();
        if (profile?.role === 'admin') isAdmin = true;
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
          zIndex={99999}
          showSpinner={false}
          template='<div class="bar" role="bar" style="display:none"><div class="peg"></div></div><div class="fixed inset-0 z-[99999] flex items-center justify-center bg-black/50 backdrop-blur-sm animate-in fade-in duration-300"><div class="bg-white dark:bg-zinc-900 p-6 rounded-2xl shadow-xl flex flex-col items-center gap-4"><svg class="h-10 w-10 animate-spin text-blue-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg><p class="text-sm font-medium text-gray-500">Yükleniyor...</p></div></div>'
        />
         <NuqsAdapter>
           <GlobalLoaderProvider>
              <ReferralTracker />
              <Header user={user} isAdmin={isAdmin} />
              <main>
                  {children}
              </main>
              <Footer />
              <Suspense fallback={null}>
                <AuthDialog />
                <VerificationToast />
              </Suspense>
              <Toaster richColors />
              <GlobalLoader />
           </GlobalLoaderProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
